version: '3.8'


services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    networks:
      - react-chess
      
networks:
  react-chess: