"""Auto migration

Revision ID: c0742a9cbc33
Revises: 
Create Date: 2021-10-14 15:58:10.407305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0742a9cbc33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='reactchess'
    )
    op.create_index(op.f('ix_reactchess_user_id'), 'user', ['id'], unique=False, schema='reactchess')
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=256), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['reactchess.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reactchess'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info', schema='reactchess')
    op.drop_index(op.f('ix_reactchess_user_id'), table_name='user', schema='reactchess')
    op.drop_table('user', schema='reactchess')
    # ### end Alembic commands ###